---

- name: Download NeoFS S3 GW binary 
  ansible.builtin.get_url:
    url: '{{ neofs_s3__gw_bin_url }}'
    dest: '{{ neofs_s3__bin_path }}/neofs-s3-gw' 
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: [ 'Restart NeoFS S3 service' ]
  when: neofs_s3__binaries_download | bool

- name: Download S3 Authmate binary 
  ansible.builtin.get_url:
    url: '{{ neofs_s3__auth_bin_url }}'
    dest: '{{ neofs_s3__bin_path }}/neofs-s3-authmate' 
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: neofs_s3__binaries_download | bool
