---

- ansible.builtin.include_tasks: user.yml


- name: Create configuration directory parent
  ansible.builtin.file:
    state: directory
    path: '{{ neofs_s3__conf_dir | realpath | dirname }}'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Create configuration directory
  ansible.builtin.file:
    state: directory
    path: '{{ neofs_s3__conf_dir }}'
    owner: 'root'
    group: '{{ neofs_s3__group }}'
    mode: '0750'

- name: Copy NeoFS S3 config
  ansible.builtin.template:
    src: 'config.yaml.j2'
    dest: '{{ neofs_s3__conf_dir }}/config.yaml'
    owner: 'root'
    group: '{{ neofs_s3__group }}'
    mode: '0640'
  notify: [ 'Restart NeoFS S3 service' ]

- ansible.builtin.include_tasks: wallet.yml

- ansible.builtin.include_tasks: binary.yml
  when: neofs_s3__binaries_download|bool

- ansible.builtin.include_tasks: auth_pregen.yml

- name: Copy systemd unit
  ansible.builtin.template:
    src: 'neofs-s3.service.j2'
    dest: '/etc/systemd/system/neofs-s3.service'
  notify: [ 'Restart NeoFS S3 service' ]
